<a href="https://colab.research.google.com/github/26wh5a0509-beep/26WH5A0509../blob/main/linearalgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 0, 1])
print(np.dot(a, b))
print(np.cross(a, b))
print(np.linalg.norm(a))
print(np.linalg.norm(a, 1))
cos = (a @ b) / (np.linalg.norm(a) * np.linalg.norm(b))
print(cos)

7
[ 2 11 -8]
3.7416573867739413
6.0
0.4537426064865151


In [6]:
import numpy as np
v = np.array([2, 5, 1]) # vector, shape (3,)
M = np.array([[1, 2], [3, 4]]) # matrix, shape (2, 2)
T = np.ones((3, 2, 2)) # tensor, shape (3, 2, 2)

In [8]:
import numpy as np
A = np.array([[2., 1.],
              [1., 3.]])
B = np.array([[1., 2.],
              [3., 4.]])
Q = np.array([[0., -1.],
              [1.,  0.]])
print(A @ B)
print(A.T)
print(np.linalg.inv(A))
print(np.trace(A))
print(np.allclose(A, A.T))
print(np.allclose(Q.T @ Q, np.eye(2)))

[[ 5.  8.]
 [10. 14.]]
[[2. 1.]
 [1. 3.]]
[[ 0.6 -0.2]
 [-0.2  0.4]]
5.0
True
True


In [10]:
import numpy as np
theta = np.radians(25)
R = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta),  np.cos(theta)]
])
point = np.array([1., 0.])
rotated_point = R @ point
print(R)
print(rotated_point)

[[ 0.90630779 -0.42261826]
 [ 0.42261826  0.90630779]]
[0.90630779 0.42261826]


In [12]:
import numpy as np
A = np.array([[2., 0.],
              [0., 3.]])
vals, vecs = np.linalg.eig(A)
print(vals)       # eigenvalues
print(vecs)       # eigenvectors
print(np.allclose(A @ vecs[:, 0], vals[0] * vecs[:, 0]))

[2. 3.]
[[1. 0.]
 [0. 1.]]
True


In [13]:
import numpy as np
A = np.array([
    [2, 1, -1],
    [-3, -1, 2],
    [-2, 1, 2]
])
b = np.array([8, -11, -3])
x = np.linalg.solve(A, b)
print(x)
print(np.linalg.matrix_rank(A))

[ 2.  3. -1.]
3


In [18]:
v = np.array([3, 4])
magnitude = np.linalg.norm(v)
print("Vector:", v)
print("Magnitude:", magnitude)

Vector: [3 4]
Magnitude: 5.0


In [19]:
A = np.array([
    [2, 1],
    [1, 3]
])
A_inverse = np.linalg.inv(A)
print("Matrix A:")
print(A)
print("\nInverse of A:")
print(A_inverse)

Matrix A:
[[2 1]
 [1 3]]

Inverse of A:
[[ 0.6 -0.2]
 [-0.2  0.4]]


In [20]:
A = np.array([
    [2, 1],
    [1, 3]
])
det = np.linalg.det(A)
print("Determinant:", det)

Determinant: 5.000000000000001


In [21]:
A = np.array([
    [2, 1],
    [1, 2]
])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[3. 1.]

Eigenvectors:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
