<a href="https://colab.research.google.com/github/26wh5a0509-beep/26WH5A0509../blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr)


[1 2 3]


In [3]:
np.array([1,2,3])
np.zeros((2,3))
np.ones((3,3))
np.full((2,2), 7)
np.arange(0,10,2)
np.linspace(0,1,5)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
arr = np.array([[1,2,3],
[4,5,6]])
arr.shape
arr.ndim
arr.size
arr.dtype
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [6]:
a = np.array([10,20,30,40,50])
a[1]
a[1:4]
a[::2]
m = np.array([[1,2],[3,4]])
m[0, 1]
m[:, 0]
a[a > 25]

array([30, 40, 50])

In [7]:
a = np.arange(6)
a.reshape(2,3)
b = np.array([1,2,3])
c = np.array([4,5,6])
np.vstack([b,c])
np.hstack([b,c])

array([1, 2, 3, 4, 5, 6])

In [8]:
a = np.array([1,4,9])
b = np.array([1,2,3])
a + b
a * b
np.sqrt(a)
np.power(b,2)

array([1, 4, 9])

In [9]:
a = np.array([[1,2,3],
[4,5,6]])
a.sum() # 21
a.sum(axis=0) # [5 7 9]
a.sum(axis=1) # [6 15]
a.mean() # 3.5
a.max()
a.argmax()

np.int64(5)

In [11]:
a = np.array([[1,2,3],
[4,5,6]])
b = np.array([10,20,30])

In [12]:
a = np.array([1,-2,3,-4,5])
a > 0
# [T F T F T]
np.where(a>0, a, 0)
# [1 0 3 0 5]
np.any(a<0) # True
np.all(a>0) # False

np.False_

In [13]:
a = np.array([3,1,4,1,5])
np.sort(a)
# [1 1 3 4 5]
np.argsort(a)
# [1 3 0 2 4]
np.unique(a)
# [1 3 4 5]

array([1, 3, 4, 5])

In [14]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A @ B
# [[19 22]
# [43 50]]
np.linalg.det(A) # -2.0
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [16]:
np.random.seed(42)
np.random.rand(2,2)
np.random.randint(1,10,5)
# [7 4 8 5 7]
a = np.array([1,2,3,4])
np.random.shuffle(a)

In [17]:
import numpy as np
scores = np.array([88, 92, 79, 95, 61, 74, 88])
print('Mean :', scores.mean())
print('Median :', np.median(scores))
print('Std Dev:', scores.std())
print('Max :', scores.max(), 'at index', scores.argmax())
passed = scores[scores >= 75]
print('Passed :', passed)
print('Pass %%:', 100 * len(passed) / len(scores))

Mean : 82.42857142857143
Median : 88.0
Std Dev: 11.043513194335821
Max : 95 at index 3
Passed : [88 92 79 95 88]
Pass %%: 71.42857142857143
